code:py
with self.assertRaises(RuntimeError):
    state.is_in_code_block()
:c
